feat: upgrade project list search to use the new search field
Unleash/unleash-frontend pull request #1073
Opened 2022-06-07 16:21 UTC by nunogois

## About the changes
https://trello.com/c/hwCvqxr9

2022-06-07 19:23 UTC, FredrikOseberg requested changes
Nice, but we might aswell place it similar to other search fields in the top right of the content container. Also, in this context is it a TableSearchField still, or should we rename it to something more general if we intend to use it for other usecases aswell?

2022-06-08 16:00 UTC, nunogois commented on src/component/common/Search/SearchSuggestions/SearchSuggestions.tsx
> +const randomIndex = (arr: any[]) => Math.floor(Math.random() * arr.length);
@sonatype-lift ignore

2022-06-10 07:18 UTC, FredrikOseberg approved these changes
Nice. Could we remove TableSearch now?

2022-06-10 13:23 UTC, merged

2022-06-13 16:08 UTC, nunogois commented
> Nice. Could we remove TableSearch now?

Agreed - This is something that can be done in the Archive tables PRs. Otherwise I can create a later PR to try and clean everything up.