Fix: UI improvements
Unleash/unleash-frontend pull request #1114
Opened 2022-06-22 14:37 UTC by Tymek

https://trello.com/c/HVvy9ov8/1316-small-fixes-in-the-ui-part-1

2022-06-23 07:11 UTC, Tymek commented
![](https://github.trello.services/images/mini-trello-icon.png) [Small fixes in the UI - Part 2](https://trello.com/c/D2laPQFd/1320-small-fixes-in-the-ui-part-2)

2022-06-27 13:25 UTC, olav requested changes

2022-06-28 06:02 UTC, Tymek commented on src/component/feedback/FeedbackCESContext/useFeedbackCESSeen.ts
> +    const isSeen = useCallback((state: IFeedbackCESState) => false, [feedback]);
😓

2022-06-28 06:22 UTC, olav approved these changes

2022-06-28 10:58 UTC, merged