Task/filter addon by project and environment
Unleash/unleash-frontend pull request #1133
Opened 2022-07-12 12:10 UTC by chriswk

This adds filtering on projects and environments to frontend and goes together with [PR 1801 in unleash/unleash](https://github.com/Unleash/unleash/pull/1801)

I do believe we might want to add some explanation before the input fields to make it clearer that adding projects/environments narrows the amount of events your addon will be notified about.

2022-07-13 11:28 UTC, chriswk commented on src/component/addons/AddonForm/AddonForm.tsx
> +                                                    editMode,
But there's no prettier configuration in the project, only ESLint?

2022-07-13 11:28 UTC, chriswk commented on src/component/addons/AddonForm/AddonForm.styles
> +import { makeStyles } from 'tss-react/mui';
Fixed, we didn't need this styles file, but I guess

2022-07-13 11:29 UTC, chriswk commented on src/component/addons/AddonForm/AddonForm.styles
> +        marginLeft: '1.5rem',
Fixed by deleting a not needed file. Same goes here though, the place where I copied this from needs to be updated as well :)

2022-07-13 11:29 UTC, chriswk commented on src/component/addons/AddonForm/AddonForm.tsx
> +                                                    editMode,
I formatted it manually for now

2022-07-13 11:30 UTC, chriswk commented on src/component/addons/AddonForm/AddonForm.tsx
> +                                                    editMode,
Ah, sorry, I see we have a fmt:check as well as the normal lint. Will use.

2022-07-13 12:05 UTC, FredrikOseberg requested changes

2022-07-13 12:05 UTC, FredrikOseberg commented on src/component/addons/AddonForm/AddonMultiSelector/AddonMultiSelector.tsx
> +    const CustomPaper = ({ ...props }) => <Paper elevation={8} {...props} />;
We should avoid creating react components inside of react components, this pattern may lead to unexpected bugs, especially with dynamic content like input fields and checkboxes.

2022-07-14 10:29 UTC, sighphyre reviewed
LGTM but I'd let the front end ninjas take one last glance here

2022-07-14 10:29 UTC, sighphyre commented on src/component/addons/AddonForm/AddonMultiSelector/AddonMultiSelector.tsx
> +            will only receive events that is tagged with one of your{' '}
```suggestion
            will only receive events that are tagged with one of your{' '}
```

2022-07-14 10:40 UTC, sighphyre approved these changes
LGTM!

2022-07-14 10:46 UTC, FredrikOseberg approved these changes
LG!

2022-07-14 10:55 UTC, merged