support offline mode, support icons and fonts
Unleash/unleash-frontend pull request #309
Opened 2021-06-19 19:12 UTC by aneeshrelan

- [x] Moved all usage of `<Icon>{icon}</Icon>` to dedicated icons from material-ui. Except the usage of dynamic application icons
- [x] Included Robot font within app.css
- [x] Validated on an offline mode with no internet

Resolves [#863](https://github.com/Unleash/unleash/issues/863)

2021-06-21 10:13 UTC, FredrikOseberg requested changes
Fantastic start. I added a few comments that we need to resolve before merging, but this is really close. 

If you can open a PR from a branch in your repository it would be easier for me to check out locally.

2021-06-21 10:13 UTC, FredrikOseberg commented on public/index.html
> -            href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700"
We need to include the fonts for the different weight types as well (300, 400, 500, 700) and add the correct font weight mapping in the @font-face ruleset. Right our fonts have only the default regular weight regardless of the CSS settings.

2021-06-21 10:13 UTC, FredrikOseberg commented on src/app.css
> +}
The font weight should be included here, as well as the other fonts.

2021-06-21 10:13 UTC, FredrikOseberg commented on src/component/addons/AddonList/ConfiguredAddons/ConfiguredAddons.jsx
> +                            {addon.enabled ? <Visibility /> : <VisibilityOff />}
```suggestion
                           <ConditionallyRender 
                                  condition={addon.enabled} 
                                  show={<Visibility />} 
                                  elseShow={<VisibilityOff />}
                            />
```

2021-06-21 10:13 UTC, FredrikOseberg commented on src/component/menu/drawer.jsx
> +function getIcon(IconComponent) {
The "library_books" icon is actually coming from our API, which will override the default setting you are setting in the reducer further down and render `<library_books>` into the DOM causing a warning. We need to add a check here for "library_books" like we are doing with the github icon.

2021-06-21 10:13 UTC, FredrikOseberg commented on src/store/ui-config/index.js
> +            icon: LibraryBooks,
This is coming dynamically from the API and will override these defaults. See the comment above.

2021-06-21 16:09 UTC, aneeshrelan reviewed
> Fantastic start. I added a few comments that we need to resolve before merging, but this is really close.
> 
> If you can open a PR from a branch in your repository it would be easier for me to check out locally.

Thanks for the initial feedback. I'll resolve in a couple of days, if that's okay and probably re-create the PR to change the source branch

2021-06-22 07:07 UTC, FredrikOseberg commented on public/index.html
> -        <link
Yes you're correct. We'll keep it in place for now.

2021-06-26 12:55 UTC, closed without merging