fix: add logout as an explicit call
Unleash/unleash-frontend pull request #311
Opened 2021-06-28 18:26 UTC by ivarconr

2021-06-29 08:27 UTC, FredrikOseberg requested changes
Looks good, due to some changes that were done in the meanwhile we need to change how we retrieve the icon.

2021-06-29 08:27 UTC, FredrikOseberg commented on src/component/menu/drawer.jsx
> +                    {getIcon('exit_to_app')}
Just merged a PR on the offline capabilities. With these changes, this needs to be changed to: 

```
import IconName from 'material-ui/core'

getIcon(IconName)
```

2021-06-29 08:32 UTC, FredrikOseberg commented
> I have not removed the LogoutComponent and the logout logic from the stores. Would we like to keep that around, or should I just remove it all?

I'd like to get rid of it, but we are currently using user.authDetails to determine whether or not a user is authenticated in the frontend. If we no longer update this on logout, we need another method of determining user authentication.

2021-06-29 09:41 UTC, ivarconr commented
> If we no longer update this on logout, we need another method of determining user authentication.

we kind of do because we instructs the browser to clear all cookies and local storage, so the authDetails will be gone after the server-side redirect.

2021-07-19 08:57 UTC, chriswk commented on src/component/menu/__tests__/routes-test.jsx
> +    expect(baseRoutes.length).toEqual(11);
```suggestion
    expect(baseRoutes).toHaveLength(11);
```

2021-07-20 20:56 UTC, merged