fix: replace empty name for admin in project access
Unleash/unleash-frontend pull request #744
Opened 2022-02-23 22:38 UTC by ykhedher

2022-02-24 19:03 UTC, ykhedher commented
![](https://github.trello.services/images/mini-trello-icon.png) [UI Inconsistencies](https://trello.com/c/cvM0vsCE/898-ui-inconsistencies)

2022-02-25 14:52 UTC, olav requested changes

2022-02-25 14:52 UTC, olav commented on src/component/project/ProjectAccess/ProjectAccessAddUser/ProjectAccessAddUser.tsx
> +        console.log(option);
:eyes:

2022-02-28 07:03 UTC, olav approved these changes

2022-03-01 15:33 UTC, merged