feat: search toggles in project
Unleash/unleash-frontend pull request #758
Opened 2022-02-28 15:28 UTC by ykhedher

2022-02-28 15:29 UTC, ykhedher commented
![](https://github.trello.services/images/mini-trello-icon.png) [Frontend - Project page search](https://trello.com/c/pI4VyN5g/900-frontend-project-page-search)

2022-02-28 16:03 UTC, ykhedher commented
![](https://github.trello.services/images/mini-trello-icon.png) [project search](https://trello.com/c/bbFsqn5w/913-project-search)

2022-03-01 07:17 UTC, olav requested changes

2022-03-01 07:17 UTC, olav commented on src/component/project/Project/ProjectFeatureToggles/ProjectFeatureToggles.styles.ts
> +        height: '35px',
`35`

2022-03-01 07:17 UTC, olav commented on src/component/common/SearchField/styles.js
>          marginRight: '8px',
`px` values can be numbers:

```
marginRight: 8,
```

2022-03-01 07:17 UTC, olav commented on src/component/project/Project/ProjectFeatureToggles/ProjectFeatureToggles.tsx
> +    useState<IFeatureToggleListItem[]>(features);
Looks unused.

2022-03-01 07:17 UTC, olav commented on src/component/project/Project/ProjectFeatureToggles/ProjectFeatureToggles.tsx
> +            ? features?.filter(feature => regExp.test(feature?.name))
Looks like `features` will always be defined, so we can drop the `?`. Same for `feature.name`.

2022-03-01 07:17 UTC, olav commented on src/component/project/Project/ProjectFeatureToggles/ProjectFeatureToggles.tsx
> +                condition={filteredFeatures?.length > 0}
Can remove `?` here as well.

2022-03-01 07:17 UTC, olav commented on src/component/project/Project/ProjectFeatureToggles/ProjectFeatureToggles.tsx
> -export default ProjectFeatureToggles;
:clap:

2022-03-01 07:17 UTC, olav commented on src/component/common/ResponsiveButton/ResponsiveButton.tsx
> +    className,
Looks unused.

2022-03-01 07:17 UTC, olav commented on src/component/project/Project/ProjectFeatureToggles/ProjectFeatureToggles.tsx
>  interface IProjectFeatureToggles {
`IProjectFeatureTogglesProps`

2022-03-01 08:38 UTC, olav approved these changes

2022-03-01 15:40 UTC, merged