feat: add search in projects
Unleash/unleash-frontend pull request #759
Opened 2022-02-28 16:04 UTC by ykhedher

2022-02-28 16:04 UTC, ykhedher commented
![](https://github.trello.services/images/mini-trello-icon.png) [project search](https://trello.com/c/bbFsqn5w/913-project-search)

2022-03-01 08:41 UTC, olav requested changes

2022-03-01 08:41 UTC, olav commented on src/component/project/ProjectList/ProjectList.styles.ts
> +        minWidth: '450px',
`450`

2022-03-01 08:41 UTC, olav commented on src/component/project/ProjectList/ProjectList.tsx
> +            ? projects?.filter(project => regExp.test(project?.name))
Looks like `projects` will always be defined, so we don't need the `?`. Same for `project?.name`.

2022-03-01 08:41 UTC, olav commented on src/component/project/ProjectList/ProjectList.tsx
> +        return filteredProjects?.map((project: IProjectCard) => {
-`?`

2022-03-01 08:41 UTC, olav commented on src/component/project/ProjectList/ProjectList.tsx
> +                        condition={filteredProjects?.length < 1 && !loading}
-`?`

2022-03-01 09:00 UTC, olav approved these changes

2022-03-01 15:55 UTC, merged