feat: add changeRole
Unleash/unleash-frontend pull request #768
Opened 2022-03-03 15:44 UTC by ykhedher

2022-03-03 15:57 UTC, ykhedher commented
![](https://github.trello.services/images/mini-trello-icon.png) [Implement the new endpoint for updating roles in the frontend](https://trello.com/c/5OVFZnQg/777-implement-the-new-endpoint-for-updating-roles-in-the-frontend)

2022-03-03 17:22 UTC, FredrikOseberg approved these changes
LGTM. But merge the backend first.

2022-03-04 07:08 UTC, olav requested changes

2022-03-04 07:08 UTC, olav commented on src/hooks/api/actions/useProjectApi/useProjectApi.ts
> +    };
Can be simplified a bit:

```
const changeUserRole = async (
    projectId: string,
    roleId: number,
    userId: number
) => {
    const path = `api/admin/projects/${projectId}/users/${userId}/roles/${roleId}`;
    const req = createRequest(path, { method: 'PUT' });
    
    return makeRequest(req.caller, req.id);
};
```

2022-03-04 09:57 UTC, olav approved these changes

2022-03-07 08:26 UTC, merged