feat: segments
Unleash/unleash-frontend pull request #776
Opened 2022-03-09 17:14 UTC by ykhedher

2022-03-09 18:56 UTC, ykhedher commented
![](https://github.trello.services/images/mini-trello-icon.png) [Segments frontend](https://trello.com/c/FG54gVeQ/926-segments-frontend)

2022-03-09 18:56 UTC, ykhedher commented
![](https://github.trello.services/images/mini-trello-icon.png) [Segments frontend](https://trello.com/c/FG54gVeQ/926-segments-frontend)

2022-03-09 18:56 UTC, ykhedher commented
![](https://github.trello.services/images/mini-trello-icon.png) [Segments frontend](https://trello.com/c/FG54gVeQ/926-segments-frontend)

2022-03-14 09:55 UTC, olav requested changes

2022-03-14 09:55 UTC, olav commented on src/component/menu/routes.js
> +        path: '/segments',
I think we'll need a UI config flag to hide the segments pages for initial testing. Maybe `SE`?

2022-03-14 09:55 UTC, olav commented on src/component/segments/SegmentList/SegmentList.tsx
> +                    setCurrentSegment={setCurrentSegment}
We can drop the error annotation by changing the state to:

```ts
const [currentSegment, setCurrentSegment] = useState<ISegment>();
```

...and the prop to:

```ts
setCurrentSegment: React.Dispatch<React.SetStateAction<ISegment | undefined>>
```

2022-03-14 09:55 UTC, olav commented on src/component/segments/SegmentList/SegmentList.tsx
> +                    onClick={() => {}}
Should be a link (not a button). Could make a placeholder page for now.

2022-03-14 09:55 UTC, olav commented on src/component/segments/SegmentList/SegmentList.tsx
> +                //@ts-expect-error
Avoid the annotation by checking `currentSegment`, something like:

```ts
{currentSegment && (
    <SegmentDeleteConfirm
        segment={currentSegment}
        open={delDialog}
        setDeldialogue={setDelDialog}
        handleDeleteSegment={onDeleteSegment}
        confirmName={confirmName}
        setConfirmName={setConfirmName}
    />
)}
```

2022-03-14 09:55 UTC, olav commented on src/component/segments/SegmentList/SegmentList.tsx
> +            <br />
Instead of using a `<br />` for styling, how about some extra padding on the container?

2022-03-14 09:55 UTC, olav commented on src/hooks/api/actions/useSegmentsApi/useSegmentsApi.ts
> +            user: JSON.stringify(user),
Remove.

2022-03-14 09:55 UTC, olav commented on src/component/segments/SegmentList/SegmentList.tsx
> +                text: 'Your segment is now deleted',
We can probably remove the toast text here.

2022-03-14 09:55 UTC, olav commented on src/component/segments/SegmentList/SegmentList.tsx
> +                    permission={ADMIN}
There are new permissions for `CREATE/UPDATE/DELETE_SEGMENT` that we should use here.

2022-03-14 17:54 UTC, FredrikOseberg commented on src/component/segments/SegmentList/SegmentList.tsx
> +            {currentSegment && (
And here

2022-03-14 17:54 UTC, FredrikOseberg commented on src/component/segments/Segments.tsx
> +export const Segment = () => {
Why do we need this component? Can't the SegmentList handle this?

2022-03-14 17:56 UTC, FredrikOseberg commented on src/component/segments/SegmentDeleteConfirm/SegmentDeleteConfirm.tsx
> +            <Alert severity="error">Danger. TEXT HERE</Alert>
Should there be some text here?

2022-03-14 17:57 UTC, FredrikOseberg requested changes
Nice. Close to done, but minor things we can do to improve it before we merge.

2022-03-16 12:19 UTC, merged