feat: add formatOperatorName
Unleash/unleash-frontend pull request #827
Opened 2022-03-29 10:28 UTC by ykhedher

2022-03-29 10:46 UTC, olav requested changes

2022-03-29 10:46 UTC, olav commented on src/utils/operatorUtils.ts
> +const formattedOperators: Record<string, string> = {
Could be ` const formattedOperators: Record<Operator, string>`

2022-03-29 10:59 UTC, olav approved these changes

2022-03-29 16:45 UTC, ykhedher commented
![](https://github.trello.services/images/mini-trello-icon.png) [Frontend Constraints - add readable operator names](https://trello.com/c/aMYVgCfn/939-frontend-constraints-add-readable-operator-names)

2022-04-04 10:39 UTC, olav commented
Fixed by https://github.com/Unleash/unleash-frontend/pull/848.

2022-04-04 10:39 UTC, closed without merging